name: Andrew-Kulpa/create-release
description: |
  Github Action for Uploading Release Artifacts
author: Andrew Kulpa
branding:
  icon: package
  color: green
inputs:
  tag: #There are two steps required to use this action:
  # - create an action inside your repo by creating a file .github/workflows/release.yml 
  # - That is where your action will be invoked.
  # The Second is to  make certain your binary artifacts are generated.
  # - You can do this by adding a project-specific .github/build script.

    required: true
  name: Uploading Artifacts
    default: ''
  body:
    default: ""
  prerelease:
    default: false
  overwrite:
    default: false
  artifacts:
    default: ""
  artifact:
    default: ''
env:
  GITHUB_TOKEN: 'Github Auth Token'
runs:
  using: node12
  main: lib/main/main.js
